### ISSUE TITLE
Koios pools query returns null ( bug / feature? )

### ISSUE THREAD

**Issue by Jack-0** [cardano-community/koios-artifacts#109]
Reference https://github.com/cardano-community/guild-operators/issues/1465

There is still an issue here. I've been writing an API that checks pools unfortunately some of the data is null for certain tickers. Including that same ticker mentioned above... 

# Reproduce
1. fetch all data from https://api.koios.rest/#get-/pool_list 
2. Notice that some fields are null
3. **here are some pools that have a null ticker**

```
high: pool1tay8z4sq4a4gmyhnygyt0t5j84z8epwjra06wq28jnnmschkkuu 
tcatl: pool1gduk8s5stt3uej5nl9vs7marx8jjyeadwz3505gzvuqey2lch35 
zebra: pool16sm29hg3qrk5lyp74qcljt38l86v5zvg95395h9gqrn6qe97d9z 
maple: pool1xpfe5q3v3axrjdc8h38taaa93frq3m9pfewxk46x4r6jgy2yj5n 
```

Is this expect behavior for Koios? 

# Context 
I know it maybe possible to find this data from pool history using the pool bech32. However, the challenge I face is I want to get a pools info when only knowing it's ticker. If some tickers are null this is not achievable as far as I am aware with Koios.

1. I query all ~3000 pools. 
2. I filter the list by ticker
3. As a few entries are null, I never find the target pool

This could be classed as a **feature** if this is the expected behavior of Koios. However, other sites/api's still display the pools tickers the only issue I found was with [high] on Cardanoscan.io

### If you don't classify this as a bug could this be turned into a feature request. I'm opening this ticket on this issue again for context.

_Originally posted by @Jack-0 in https://github.com/cardano-community/guild-operators/issues/1465#issuecomment-1272616685_

**Comment by rdlrt** [comment]
The above mentioned tests from Boris' fork (cherry picked dbsync commits) look promising, the fixes made upstream to dbsync are now showing all the mentioned pools - awaiting a release (or even a dedicated tag/branch on IO repo) on dbsync now

**Comment by rdlrt** [comment]
Update - still waiting to hear back on marking next tag/release on dbsync

**Comment by reqlez** [comment]
> Update - still waiting to hear back on marking next tag/release on dbsync

I have not seen any additional commits into that branch 13-0-6 branch, i'm assuming they are getting some obscure release manager on it lol
