### ISSUE TITLE
Koios 1.0.8 PreProd: Royalty token metadata is not returned in /asset_info but only in /asset_history

### ISSUE THREAD

**Issue by maxee** [cardano-community/koios-artifacts#111]
**Describe the bug**
We're using Koios 1.0.8 (although it could be that earlier versions are also affected) on **preprod**.

When fetching the information about a royalty token via `/asset_info`, the metadata field is empty.

When fetching the information about a royalty token via `/asset_history`, the metadata field is filled with the correct metadata as expected.

asset_info:

```json
[{"policy_id":"52c4e5bd954271ef717936cbb9a2efa39f6f79a4885d44cb57492d97","asset_name":"","asset_name_ascii":"","fingerprint":"asset1kuvuc0avygjcgtuwdkp4tl0f89mjmqz5u4378s","minting_tx_hash":"315baf46af9cdc51a8ce9670c0ba8ac0cdc73c514d553e48f85bf438c24be025","total_supply":"0","mint_cnt":1,"burn_cnt":1,"creation_time":1665573938,"minting_tx_metadata":{},"token_registry_metadata":null}]
```

asset_history:

```json
[{"policy_id":"52c4e5bd954271ef717936cbb9a2efa39f6f79a4885d44cb57492d97","asset_name":"","minting_txs":[{"tx_hash" : "148811d50311974d73a8baca624e691c436a517b95410a3ec66e8f7d4c77d367", "block_time" : 1665573956, "quantity" : "-1", "metadata" : [{"key" : null, "json" : null}]},{"tx_hash" : "315baf46af9cdc51a8ce9670c0ba8ac0cdc73c514d553e48f85bf438c24be025", "block_time" : 1665573938, "quantity" : "1", "metadata" : [{"key" : "777", "json" : {"pct": "0.3", "addr": ["addr_test1qrqppj2vjwa7v55r9yafj3n3nwf80ve95z4s0eu8k7zh9wkp28sfx9", "9tcvp3ats0g59vfuam4jz3hx284dr9zseag75qnzymfz"]}}]}]}]
```

**To Reproduce**
1. Call `/api/v0/asset_info?_asset_policy=52c4e5bd954271ef717936cbb9a2efa39f6f79a4885d44cb57492d97&_asset_name=`
2. Metadata is not included
3. Call `/api/v0/asset_history?_asset_policy=52c4e5bd954271ef717936cbb9a2efa39f6f79a4885d44cb57492d97&_asset_name=`
4. Metadata is included

**Expected behavior**
The `/asset_info` response should also include the royalty token metadata.

**Additional context**

On the official Koios legacy testnet instance, the behavior cannot be reproduced:

https://testnet.koios.rest/api/v0/asset_info?_asset_policy=5873e09ab65389ce8249a4dbd401f14bb2149f29b9e5a05d5ba47330&_asset_name=

https://testnet.koios.rest/api/v0/asset_history?_asset_policy=5873e09ab65389ce8249a4dbd401f14bb2149f29b9e5a05d5ba47330&_asset_name=

**Comment by rdlrt** [comment]
Do you encounter this on any of the testnet/mainnet assets?
Difficult to troubleshoot Preprod , not being in supported list - unless we stand up an instance specifically for this issue

**Comment by maxee** [comment]
@rdlrt 
I have one more policy to reproduce the issue in preprod:
`/api/v0/asset_info?_asset_policy=8c7cb81f6810820de4e6a410fb1c73b18abdba71baa1daaeca671987&_asset_name=`
`/api/v0/asset_history?_asset_policy=8c7cb81f6810820de4e6a410fb1c73b18abdba71baa1daaeca671987&_asset_name=`


As noted in the original issue, I was not able to reproduce it in testnet, however the policy I tested hat *multiple* policy keys added to the royalty token mint.


I searched for some mainnet policies, there the same bug/behavior can be reproduced:

Policy 1:

https://api.koios.rest/api/v0/asset_info?_asset_policy=dac355946b4317530d9ec0cb142c63a4b624610786c2a32137d78e25&_asset_name=

```json
[{"policy_id":"dac355946b4317530d9ec0cb142c63a4b624610786c2a32137d78e25","asset_name":"","asset_name_ascii":"","fingerprint":"asset1pxklrcqcnhgjffqz75dgvmeyzma3av5w3x4xnr","minting_tx_hash":"52c5e174ab536c55f1ab1a12efce4010e384658fe49152ced66b221f1b5e14a0","total_supply":"0","mint_cnt":1,"burn_cnt":1,"creation_time":1643309991,"minting_tx_metadata":{},"token_registry_metadata":null}]
```

https://api.koios.rest/api/v0/asset_history?_asset_policy=dac355946b4317530d9ec0cb142c63a4b624610786c2a32137d78e25&_asset_name=

```json
[{"policy_id":"dac355946b4317530d9ec0cb142c63a4b624610786c2a32137d78e25","asset_name":"","minting_txs":[{"tx_hash" : "0b3f826d7882ae14bc7cf60987a1a05332709fd42701cc40bd9256b3674370d1", "block_time" : 1643310754, "quantity" : "-1", "metadata" : [{"key" : null, "json" : null}]},{"tx_hash" : "52c5e174ab536c55f1ab1a12efce4010e384658fe49152ced66b221f1b5e14a0", "block_time" : 1643309991, "quantity" : "1", "metadata" : [{"key" : "777", "json" : {"pct": "0.05", "addr": ["addr1qxsgnhj482auc7cl7qwy75tkadv6eeudaatcr38ffe8hfreelz428zq6sv8", "d6vht3t29ud5nzmgyl9cvhyf6apa7888snufxnj"]}}]}]}]
```


Policy 2:

https://api.koios.rest/api/v0/asset_info?_asset_policy=c56d4cceb8a8550534968e1bf165137ca41e908d2d780cc1402079bd&_asset_name=

```json
[{"policy_id":"c56d4cceb8a8550534968e1bf165137ca41e908d2d780cc1402079bd","asset_name":"","asset_name_ascii":"","fingerprint":"asset15pqxdfguku7q322jkxhlc5q3rhffukh04jt5wq","minting_tx_hash":"def1664c2bf280db01ff7d60daa77f85756d50e1196dc0dd3808d9856471b683","total_supply":"0","mint_cnt":1,"burn_cnt":1,"creation_time":1638987411,"minting_tx_metadata":{},"token_registry_metadata":null}]
```

https://api.koios.rest/api/v0/asset_history?_asset_policy=c56d4cceb8a8550534968e1bf165137ca41e908d2d780cc1402079bd&_asset_name=

```json
[{"policy_id":"c56d4cceb8a8550534968e1bf165137ca41e908d2d780cc1402079bd","asset_name":"","minting_txs":[{"tx_hash" : "19bf09e072697237c146ae29e52608c6c8222d442bd2b6abf5200b8a5dcebf90", "block_time" : 1638987439, "quantity" : "-1", "metadata" : [{"key" : null, "json" : null}]},{"tx_hash" : "def1664c2bf280db01ff7d60daa77f85756d50e1196dc0dd3808d9856471b683", "block_time" : 1638987411, "quantity" : "1", "metadata" : [{"key" : "777", "json" : {"pct": "0.03", "addr": ["addr1q8f73cvhvka0kaw297uxp8l66yn9rzdqrt6k27ucwc3le3a36q5wz44d5yj", "vlgkpkrdvnua8cpv73kl7awjwzvvj6vvshaueq2"]}}]}]}]
```


I'm not really sure, maybe the issue is that `/asset_info` is considering the latest TX the asset is involved - which should be for the royalty tokens the burn TX which has no metadata attached?

**Comment by rdlrt** [comment]
Thanks for reporting, will be applied as part of linked PR
