### ISSUE TITLE
Add Next Epoch Nonce

### ISSUE THREAD

**Issue by QuixoteSystems** [cardano-community/koios-artifacts#114]
**Is your feature request related to a problem? Please describe.**
I think is a useful feature adding a query to get next epoch parameters (overall nonce) from 1.5 days before current epoch ends.

**Describe the solution you'd like**
New query where we can ask for next epoch parameters, I think is really useful next epoch Nonce, to use in a bunch calculations.

**Describe alternatives you've considered**
Use current query but if you call with next epoch number, the query give you next epoch parameters.

**Additional context**
I want to use for [Cardano Leader Slot script](https://github.com/QuixoteSystems/cardano-leader-slot)

**Comment by rdlrt** [comment]
To do:
- populate epoch cache to include output from `echo "$(cardano-cli query protocol-state --testnet-magic 141 | jq -r .candidateNonce.contents)$(cardano-cli query protocol-state --testnet-magic 141| jq -r .lastEpochBlockNonce.contents)" | xxd -r -p | b2sum -b -l 256 | awk '{print $1}'`
