### ISSUE TITLE
Add total_suppy field on account assets and address assets. 

### ISSUE THREAD

**Issue by HT-Moh** [cardano-community/koios-artifacts#119]
At the moment the only way to filter assets policies (FT and NFT) is by using the `total_supply`, if we want to filter account assets we need to do a call to `asset_info` for each asset, so for a wallet with 100 `assets_info` we need 100 calls, this lot of network requests. 
is there a possibility to add total_supply to `account_assets`  and `address_assets`?
The [CIP-0067](https://github.com/cardano-foundation/CIPs/pull/298#top)  gives the possibility to classify the asset from the name but it's not adopted yet ;-)

**Comment by rdlrt** [comment]
TBD - consideration to be put in asset object consistency

**Comment by Scitz0** [comment]
Asset cache table should include the following fields:
asset_id, total_supply, first_mint_tx_id, first_mint_keys, last_mint_tx_id, last_mint_keys, decimals

**Comment by Scitz0** [comment]
Superseded by #124
