### ISSUE TITLE
Added 1 field to display decimals in api https://api.koios.rest/api/v0/account_assets

### ISSUE THREAD

**Issue by DCOneCrypto** [cardano-community/koios-artifacts#127]
Added 1 field to display decimals in api https://api.koios.rest/api/v0/account_assets. If we need to display the correct balance to the account balance we need to make the asset_info call for each asset to get the "decimals" field, so for wallets with nft > 100 tokens we need > 100 call command. Example "assets": [
       {
         "policy_id": "29d222ce763455e3d7a09a665ce554f00ac89d2e99a1a83d267170c6",
         "assets": [
           {
             "asset_name": "4d494e",
             "asset_name_ascii": "MIN",
             "balance": "1859630215"
           },
           {
             "asset_name": "4d494e74",
             "asset_name_ascii": "MINt",
             "balance": "1842795018"
           }
         ]
       },
.But my wallet MIN balance is only 1859 and Mint balance is only 1842.
Thank you for your interest

**Comment by Scitz0** [comment]
Dependent on #124 
Add decimals to all asset objects that contain quantity.

**Comment by DCOneCrypto** [comment]
Yes!.

**Comment by DCOneCrypto** [comment]
> Dependent on #124 Add decimals to all asset objects that contain quantity.

Yes! Wish to add decimals to all tokens with quantity

**Comment by rdlrt** [comment]
Fixed by linked PR, will be part of koios-1.0.10
