### ISSUE TITLE
datum_hashes examples do not have good example payload

### ISSUE THREAD

**Issue by mkungla** [cardano-community/koios-artifacts#136]
e.g.  Guildnet example has duplicated example hash `45b0cfc220ceec5b7c1c62c4d4193d38e4eba48e8815729ce75f9c0ab0e4c1c0` which is also shared with `mainnet` example (seems that this is not correct hash)

https://github.com/cardano-community/koios-artifacts/blob/2423de37e437f990861e5a90639df3ee2d3988c9/specs/templates/example-map.json#L208-L221

**Comment by rdlrt** [comment]
Closed in linked PR
