### ISSUE TITLE
Query multiple assets feature request

### ISSUE THREAD

**Issue by Jack-0** [cardano-community/koios-artifacts#138]
Currently you can use https://api.koios.rest/#get-/asset_info to query a single asset. In real world usage a user may want to query multiple assets.

Would it be possible add a new route to query multiple assets via a **fingerprint array** or via a **tuple of policy and asset name array**?

Currently the single asset query combined with 100 requests per 10 seconds makes Koios unfeasible for applications that query many assets. 

Kind regards, Jack.

**Comment by rdlrt** [comment]
Could you clarify what all information are must for bulk information for an asset

There is going to be a cache addition soon that will likely assist with 'some' of the information  - but we need to be mindful of resources given the amount of spammy operations in DeFi world, so would have to start with minimal viable information to start

**Comment by rdlrt** [comment]
Fixed by linked PR, will be part of koios 1.0.10
