### ISSUE TITLE
Wrong value deleg_rewards in Pool History endpoint

### ISSUE THREAD

**Issue by ducpm2303** [cardano-community/koios-artifacts#203]
There is an issue with the value delegators reward on Koios, which is different from (db-sync, cexplorer). 
I have tried various combinations of pool and epoch parameters, but the output is consistently inaccurate with (db-sync, cexplorer)

Test data: pool = pool1z5uqdk7dzdxaae5633fqfcu2eqzy3a3rgtuvy087fdld7yws0xt, epoch = 412.
The different values are presented below:

- Koios:  deleg_rewards: **28975165130**
`curl -X GET "https://api.koios.rest/api/v0/pool_history?_pool_bech32=pool1z5uqdk7dzdxaae5633fqfcu2eqzy3a3rgtuvy087fdld7yws0xt&_epoch_no=412" \
 -H "accept: application/json" `

 - Db-sync: deleg_rewards: **28741480068**
 `select sum(r.amount) from reward r where r.pool_id = 1 and r.earned_epoch = 412 and r."type" = 'member'`
 
 - Cexplorer:  deleg_rewards: **28741480068** same with db-sync
 https://cexplorer.io/pool/pool1z5uqdk7dzdxaae5633fqfcu2eqzy3a3rgtuvy087fdld7yws0xt/rewards#data

**Comment by rdlrt** [comment]
I think there is some ambiguity here, perhaps we should better clarify in the endpoint details itself.
1. `Member` is not the same as `Delegator`. By definition, a pool will not incur any rewards if the owners themselves are not delegated to the same pool. From protocol point of view, Owner(s) are also part of delegators list (which is consistent with number of delegators for a pool), you need to add the leader members to include their share of delegation rewards (i.e. excluding pool fees). Accordingly, the endpoint does provide **delegator** rewards - but does not make a distinction for owner (in fact, it does go out of the way to include owner's reward portion into delegator value). Perhaps, it could be something added as a new output column (`member rewards`) to the endpoint.
2. As regards stats , what you see:
a. In reward table , you do not have `delegator` as type, you have `member` and `leader`. Thus, data you see there:
  leader rewards=836829851, member rewards=28741480068, total rewards = 29578309919
b. What you see from the Koios endpoint:
  delegator(leader+member) rewards = 28975165130, pool fees (fixed+margin) = 603144789, total rewards = 29578309919
The total in either case is the same, but the difference comes for member vs delegator.
