### ISSUE TITLE
koios.rest still links to https://testnet.koios.rest/#overview

### ISSUE THREAD

**Issue by fallen-icarus** [cardano-community/koios-artifacts#204]
**Describe the bug**
[koios.rest](https://www.koios.rest/) still links to [https://testnet.koios.rest/#overview](https://testnet.koios.rest/#overview) when looking to get the api documentation for testnet. I mistakenly took the dead link to mean that koios did not support the preview or preproduction testnets. It wasn't until I came across [preprod.koios.rest](https://preprod.koios.rest/) by accident that I realized I was wrong.

**To Reproduce**
1. Go to [koios.rest](https://www.koios.rest/)
2. On mobile, from the drop-down menu, click on `API DOCUMENTATION` then click on `Testnet`.
3. On desktop, at the top right, hover over `API DOCUMENTATION` then click on `Testnet`.

**Expected behavior**
The link should take a user to a valid documentation link for either testnet. Or, better yet, there should be an explicit option for both the preview and preproduction testnets.

**Desktop (please complete the following information):**
I'm getting the same result no matter what device and browser I use.

**Comment by rdlrt** [comment]
Thanks for the report. 
The koios.rest website is indeed a bit out of date and will be completely replaced with a new website with correct examples and live demos across networks, we are quite close to having the replacement site up.

Meanwhile, github releases and the README in root of this repo has the correct URLs.

**Comment by rdlrt** [comment]
The new website went live, thus - closing this
