### ISSUE TITLE
historic pool_list

### ISSUE THREAD

**Issue by gufmar** [cardano-community/koios-artifacts#208]
**Is your feature request related to a problem? Please describe.**
pool_info .pool_status values shows `registered` and `retiring` as values but no `retired`
Now there are several history endpoints offering _epoch_no as a query parameter, such as pool_history and pool_delegator_history
But without a complete list of pools for that epoch, I can't dig into historic informations.

**Describe the solution you'd like**
get a complete list of a specific historic epochs pool landscape

**Describe alternatives you've considered**
One idea is to query all pool updates since ep207, and then walk through from oldest to newest to build a temp set of pool_ids active in a certain epoch.
Ideally this comes cached and precalculated from an the existing pool_list or a new endpoint

**Comment by rdlrt** [comment]
Fixed in #227
