### ISSUE TITLE
Epoch information change

### ISSUE THREAD

**Issue by M4rc0Russ0** [cardano-community/koios-artifacts#218]
**Describe the bug**
When I find an epoch using the Koios API, the `tx_count`, `blk_count` and `out_sum` values are different per request.

**To Reproduce**

1. Go to ['Koios API'](https://api.koios.rest/#get-/epoch_info)
2. Click on `_epoch_no string`
3. Write `348`
4. Click on `TRY`
5. Save results
6. Click on `TRY` again
7. Compare results

**Expected behavior**
Every time someone make a request to the endpoint to get the epoch 348 should receive exactly the same information each time.

**Screenshots**
![image](https://github.com/cardano-community/koios-artifacts/assets/108673166/e2524830-7139-4226-a239-dab7e90bb8f3)
![image](https://github.com/cardano-community/koios-artifacts/assets/108673166/e9b66985-da5e-41d5-9177-336158a95ff1)

**Comment by rcmorano** [comment]
This is probably related to [this issue on cardano-db-sync](https://github.com/input-output-hk/cardano-db-sync/issues/1457), maybe some nodes are/were running different `cardano-db-sync` versions or restored from snapshots created by diff versions of it.

**Comment by rdlrt** [comment]
Even within a release, the state could differ depending on epoch cache...the instance providers have been instructed to run fixes - it should resolve in few hours

**Comment by rdlrt** [comment]
This should be sorted for now, but will keep the issue open until next release - as graceful fix will only be available on next dbsync release.
![image](https://github.com/cardano-community/koios-artifacts/assets/3169068/4c89f3a5-0369-4e4d-89db-91d6cf3b6011)

**Comment by rdlrt** [comment]
Temporary patch to fix historical entries added to cron in #227 , part of upcoming release
