### ISSUE TITLE
pool_metadata endpoint inconsistency with pool_info

### ISSUE THREAD

**Issue by Scitz0** [cardano-community/koios-artifacts#224]
pool_metadata returns the latest from dbsync, no matter if dbsync has successfully fetched the metadata and populated pool_offline_data.
This is while the pool_info endpoint will return the last valid entry in pool_offline_data for metadata while the metadata hash is always for the latest metadata, so might not match the metadata actually returned.

**Comment by rdlrt** [comment]
Fixed in #227
