### ISSUE TITLE
New Endpoint: script_execution_units_evaluation

### ISSUE THREAD

**Issue by fallen-icarus** [cardano-community/koios-artifacts#237]
**Is your feature request related to a problem? Please describe.**
Trying to build a transaction without a local node using `cardano-cli transaction build-raw` requires the user to specify the budget necessary for each plutus script in the transaction. Getting the budgets wrong will result in the transaction failing. If there is only one script, the user can just set it to the max available but if there are multiple scripts in the transaction, that approach may not work (eg, one script may require most of the available budget while other scripts barely use any). Knowing the exact budget required for each script would dramatically improve the experience of composing plutus scripts without relying on a local node.

**Describe the solution you'd like**
I am looking for something like what blockfrost has [here](https://blockfrost.dev/api/submit-a-transaction-for-execution-units-evaluation). The user should be able to submit a transaction created with `cardano-cli transaction build-raw` and the query should return the breakdown of execution units used for each script. The user would then take those budget numbers and recreate the transaction using the `build-raw` command for actual submission to the blockchain.

**Describe alternatives you've considered**
The only current alternatives I am aware of are to use a local node or use blockfrost.

**Comment by rdlrt** [comment]
Duplicate being tackled already via #227
