### ISSUE TITLE
\address_utxos endpoint does not properly return reference script information

### ISSUE THREAD

**Issue by fallen-icarus** [cardano-community/koios-artifacts#244]
**Describe the bug**
I submitted a transaction with the hash c68dba0247b5f8548bfc9fca7b1c18ce741af03d3d1b9ea7af4069ead5924af3 to the preproduction testnet. Using the \tx_info endpoint, I can see the outputs with the reference scripts. Here is the exact command I used:
``` Bash
curl -sX POST "https://preprod.koios.rest/api/v1/tx_info?select=outputs"  -H "accept: application/json" -H "content-type: application/json"  -d '{"_tx_hashes":["c68dba0247b5f8548bfc9fca7b1c18ce741af03d3d1b9ea7af4069ead5924af3"]}' 
```
There are only three outputs and two of them have reference scripts. However, when I then use the \address_utxos endpoint, it says that none of the outputs have reference scripts. Here is the exact command I used:
```Bash
curl -sX POST -H "content-type: application/json" 'https://preprod.koios.rest/api/v1/address_utxos?tx_hash=eq.c68dba0247b5f8548bfc9fca7b1c18ce741af03d3d1b9ea7af4069ead5924af3' -d '{"_addresses":["addr_test1vrlfp27zjnjlsak5f7dnjkpl9ekeq5ezc3e4uw769y5rgtc4qvv2f" ], "_extended": true }'
```

In the response from \address_utxos, the UTxOs that are supposed to have the reference script information actually have the key/value maps that are supposed to be there, just all the values are null. The UTxO that does not actually have a reference script does not have a key/value map, instead it just has null. Here is what I mean:
```Bash
# The UTxO that is supposed to have a reference script.
"reference_script": {                                                                                                                                                                                          
      "hash": null,                                                                                                                                                                                                
      "size": null,                                                                                                                                                                                                
      "type": null,                                                                                                                                                                                                
      "bytes": null,                                                                                                                                                                                               
      "value": null                                                                                                                                                                                                
    }, 

# The UTxO that does not have a reference script.
"reference_script": null,
```
**To Reproduce**
Execute the above two commands and see the discrepancy.

**Comment by rdlrt** [comment]
Thanks for flagging, there was indeed a typo in join condition across the board for fetching reference scripts, fixed with [this commit](https://github.com/cardano-community/koios-artifacts/commit/c0145bc800bde1f5d6e15456da1e01c4f2dbe20f). Let me know if you still see an issue on preprod
