### ISSUE TITLE
address_txs endpoint returns unrelated transactions

### ISSUE THREAD

**Issue by fallen-icarus** [cardano-community/koios-artifacts#266]
**Describe the bug**
On preprod, I have this address: `addr_test1vpz6g5ecxv6mc036lckg6w06wmj7vr073j73llzpsn5t0pguw7m5u`.

When I use the address_txs endpoint, some of the transactions returned have nothing to do with the above address. Here is the exact command I am using to get the transactions for the above address:

```Bash
curl -X POST "https://preprod.koios.rest/api/v1/address_txs"  -H "accept: application/json" -H "content-type: application/json"  -d '{"_addresses":["addr_test1vpz6g5ecxv6mc036lckg6w06wmj7vr073j73llzpsn5t0pguw7m5u"]}' | jq

```
I then check the transaction information using the tx_info endpoint with this command:
```Bash
curl -X POST "https://preprod.koios.rest/api/v1/tx_info"  -H "accept: application/json" -H "content-type: application/json"  -d '{"_tx_hashes":["d9090d9714189b9e0a267344381394d6384dbeafb267f4a9d97577f5297bf1fa"]}' | jq
```

The transaction (`d909...`) in the last command does not seem relevant to my address yet it was returned by the first command; none of the collateral, reference inputs, inputs, or outputs are to/from my address. Which unrelated transactions are returned by the first command seems to change from time to time but there are usually several unrelated transactions each time. I have other addresses with shorter transaction histories and this does not seem to impact them.

Other incorrect transactions I've frequently seen:
```
faaeb9a723933c7089131e4b9da15f4f431c1289dce7c5432bb5fa714379ace2
6558ae79d5f14406c01e8efebbc29005cafec8a02b097faa37ab1429d9f862f5
```
 
**To Reproduce**
Try the above commands and check that the returned transactions actually involve the address.

**Expected behavior**
Only relevant transactions should be included.

**Comment by rdlrt** [comment]
Thanks, this was discovered yesterday - already patched as emergency on mainnet by instance providers, while will be fixed with proper release on other networks

**Comment by rdlrt** [comment]
Closing as already part of v1.1.1  - and fixed on mainnet, schedule for other networks should be published this week
