### ISSUE TITLE
asset_utxos does not accept Range header

### ISSUE THREAD

**Issue by mkungla** [cardano-community/koios-artifacts#271]
**Describe the bug**
asset_utxos returns "content_range": "0-999/*" header so I expected it would also accept `Range` header for paging

**Comment by rdlrt** [comment]
The `Range` header is only applicable for `GET` requests (see  [api doc reference](https://api.koios.rest/#overview--pagination-offsetlimit) and the [source conversation on PostgREST](https://github.com/PostgREST/postgrest/issues/2156#issuecomment-1033481329) for their design decision.

**Comment by mkungla** [comment]
I dunno then how usefull `asset_utxos` endpoint is then or what usecase it serves.

**Comment by rdlrt** [comment]
For pagination, the universal method would always be using limit/offset (as [here](https://api.koios.rest/#overview--pagination-offsetlimit)  ) with any GET/POST calls
