### ISSUE TITLE
BUG: asset_txs endpoint returns incorrect transaction list

### ISSUE THREAD

**Issue by fallen-icarus** [cardano-community/koios-artifacts#274]
**Describe the bug**
I have this asset: 
```
policy_id = ba42442d92fbdab9f1fcf814313b7df4cf19100d620a3f963c1de128
asset_name = 0f7deb6eca31425e357b1a7a9284f0e60782f5b2a36c80c5ef4b89bcbc4b5ced
```

I am trying to query all transactions involving this asset. There are six transactions in total:
```
mint_tx_hash = a4afa3648bf273c563c6b66c51110f7bfdfbe761d53a7a8e1961d79e3d53b0cd (2 were minted)
usage1 = 27fedf54ffd8c907fb5e5231a4933a5fa84ae0585097478c5dbb7fbbfcb1578d
usage2 = 234f86d19e550469b654fb9ee9e1cc94c19a481a16192df015a362125697e812
usage3 = b0c01d20f93919a725c2382cc7f0386f8cb76724d10c72f2ee672d12c9d0f2ec
burn_tx_hash1 = 49c2f433890ab1d4bba7593bf89b58e8b30afcfb567bc17a13afa83fff15c09d
burn_tx_hash2 = 99ebb861f74b52031a65467e65b9502f3e3071cb20cc1db363e910aacc179763
```

However, using the `asset_txs` endpoint with this query:
```
curl -X GET "https://preprod.koios.rest/api/v1/asset_txs?select=tx_hash&_asset_policy=ba42442d92fbdab9f1fcf814313b7df4cf19100d620a3f963c1de128&_asset_name=0f7deb6eca31425e357b1a7a9284f0e60782f5b2a36c80c5ef4b89bcbc4b5ced&_history=true"  -H "accept: application/json"
```
results in:
```json
[
  {
    "tx_hash": "b0c01d20f93919a725c2382cc7f0386f8cb76724d10c72f2ee672d12c9d0f2ec"
  },
  {
    "tx_hash": "234f86d19e550469b654fb9ee9e1cc94c19a481a16192df015a362125697e812"
  },
  {
    "tx_hash": "27fedf54ffd8c907fb5e5231a4933a5fa84ae0585097478c5dbb7fbbfcb1578d"
  },
  {
    "tx_hash": "a4afa3648bf273c563c6b66c51110f7bfdfbe761d53a7a8e1961d79e3d53b0cd"
  },
  {
    "tx_hash": "a4afa3648bf273c563c6b66c51110f7bfdfbe761d53a7a8e1961d79e3d53b0cd"
  }
]
```
There are only five transactions, and two of them are actually the same transaction (the mint transaction). The burn transactions are both excluded from the results.

**Expected behavior**
I had assumed the `asset_txs` endpoint would effectively be a super-set of the `asset_history` endpoint (ie, it would return the mint/burn transactions as well as any normal transactions).

**Additional context**
The `asset_history` endpoint returns the correct mint/burn transactions. Query used:
```
curl -X GET "https://preprod.koios.rest/api/v1/asset_history?select=minting_txs&_asset_policy=ba42442d92fbdab9f1fcf814313b7df4cf19100d620a3f963c1de128&_asset_name=0f7deb6eca31425e357b1a7a9284f0e60782f5b2a36c80c5ef4b89bcbc4b5ced"  -H "accept: application/json"
```
Result:
```json
[
  {
    "minting_txs": [
      {
        "tx_hash": "99ebb861f74b52031a65467e65b9502f3e3071cb20cc1db363e910aacc179763",
        "metadata": [],
        "quantity": "-1",
        "block_time": 1712852801
      },
      {
        "tx_hash": "49c2f433890ab1d4bba7593bf89b58e8b30afcfb567bc17a13afa83fff15c09d",
        "metadata": [],
        "quantity": "-1",
        "block_time": 1712852776
      },
      {
        "tx_hash": "a4afa3648bf273c563c6b66c51110f7bfdfbe761d53a7a8e1961d79e3d53b0cd",
        "metadata": [],
        "quantity": "2",
        "block_time": 1712851094
      }
    ]
  }
]
```

**Comment by rdlrt** [comment]
Thanks for raising, it is an interesting point. The current extractions for *_txs are based on requested object being used in the transaction itself (input/output - which is why you see a4afa... returned twice, as the asset is in two outputs of same transaction).

I agree that it makes sense to adapt, so converting to desired output, the change would be to make asset_txs differ from usual *_txs pattern as below:
1. Add asset burns (mints are already included since the output asset is part of UTxO) to this endpoint.
2. Add transaction index field to the output (so that it doesnt seem that same transaction is 'duplicated' but shows that they are two seperate input/output references).

@hodlonaut @Scitz0 - Do you agree with above change?

**Comment by Scitz0** [comment]
To me (1) makes sense to show all transactions that has an impact on the asset in question. But I'm more hesitant about (2). This endpoint is meant to give back all transactions that in some way involve the asset, not the actual utxos. We have another endpoint for this, asset_utxos. Though asset_utxos only return active utxo set. 

So for (2) above I instead propose that we solve it two ways, second being optional.

1. Make asset_txs return only unique entries and coupled with (1) from priyanks reply this would return both mint and burn but only one entry for the mint even though there are two outputs to the same transaction. 
2. Possibly add `_history` flag to asset_utxos to be able to get historical utxos for an asset just like for asset_txs.

**Comment by rdlrt** [comment]
Was just about to start working on (1) , and realised the obvious side-effect consideration on adding burn is unlike other arrangements, we would be adding a join against ma_tx_mint table, which could be a bit expensive 🙂 I suppose it's something we'd have to test and see effects of, but it could certainly increase likeliness of causing a timeout on asset_txs endpoint

**Comment by rdlrt** [comment]
@fallen-icarus , could you confirm this looks good? Result of proposed changes above (in linked PR) :
``` bash
curl "http://127.0.0.1:18050/rpc/asset_txs?_asset_policy=ba42442d92fbdab9f1fcf814313b7df4cf19100d620a3f963c1de128&_asset_name=0f7deb6eca31425e357b1a7a9284f0e60782f5b2a36c80c5ef4b89bcbc4b5ced&select=tx_hash,block_height&_history=true&order=block_height"
```
``` json
[{"tx_hash":"a4afa3648bf273c563c6b66c51110f7bfdfbe761d53a7a8e1961d79e3d53b0cd","block_height":2135567}, 
 {"tx_hash":"27fedf54ffd8c907fb5e5231a4933a5fa84ae0585097478c5dbb7fbbfcb1578d","block_height":2135579}, 
 {"tx_hash":"234f86d19e550469b654fb9ee9e1cc94c19a481a16192df015a362125697e812","block_height":2135593}, 
 {"tx_hash":"b0c01d20f93919a725c2382cc7f0386f8cb76724d10c72f2ee672d12c9d0f2ec","block_height":2135600}, 
 {"tx_hash":"49c2f433890ab1d4bba7593bf89b58e8b30afcfb567bc17a13afa83fff15c09d","block_height":2135608}, 
 {"tx_hash":"99ebb861f74b52031a65467e65b9502f3e3071cb20cc1db363e910aacc179763","block_height":2135610}]
```

**Comment by Scitz0** [comment]
> Was just about to start working on (1) , and realised the obvious side-effect consideration on adding burn is unlike other arrangements, we would be adding a join against ma_tx_mint table, which could be a bit expensive 🙂 I suppose it's something we'd have to test and see effects of, but it could certainly increase likeliness of causing a timeout on asset_txs endpoint

ma_tx_mint isn't that bad right? Its ma_tx_out that we want to avoid if possible?

**Comment by fallen-icarus** [comment]
@rdlrt That looks good to me :+1:
