### ISSUE TITLE
Feature Request: Identify input used for spending script executions

### ISSUE THREAD

**Issue by fallen-icarus** [cardano-community/koios-artifacts#277]
**Is your feature request related to a problem? Please describe.**
My protocols are composable with other protocols as well as themselves. For example, for my lending/borrowing protocol, a borrower can make a payment of 5 ADA for one loan, make a payment of 7 ADA on another loan, and make a payment of 10 ADA on a third loan. Each loan is a separate UTxO and the action taken is specified by the redeemer used to spend that UTxO.

I would like to be able to query a specific loan's event history, but this requires me to tell these loans apart when they are composed in a single transaction. The `tx_info` endpoint returns the `plutus_contracts` list, but this only includes the datum and redeemer used for an execution. This is not always enough information to match redeemers to inputs. Consider the following (simplified) example:

```
Two inputs from the same spending script, both with datum A, are spent in the same transaction.
Input 1 used redeemer X while input 2 used redeemer Y.

Koios's tx_info enpoint is queried and the plutus_contracts list says:
[ datum A + redeemer X from the script
, datum A + redeemer Y from the script
]

From the returned information, I have no way of knowing that input 1 used redeemer X while 
input 2 used redeemer Y.
```

The only exception to the above dilemma is when the datums themselves are unique; the datums can be used to identify the input that particular execution is for. However, this may not be a valid assumption for all use cases.

**Describe the solution you'd like**
When spending scripts are executed, I would like Koios to be able to tell me:
- the datum used
- the redeemer used
- the input this execution is validating

**Describe alternatives you've considered**
I don't actually have any alternatives. I can currently use the datums to identify the inputs, but newer versions of plutus my favor designs where this approach will no longer be viable for me.

**Additional Context**
I am not married to the information having to be in the `tx_info` endpoint, but I would like to be able to get the results in the fewest number of queries possible. IMO the `tx_info` is great; this feature is the only thing missing from it. If possible, my preference would be to add this feature to the `tx_info` endpoint.

**Comment by rdlrt** [comment]
Was discussed with @Scitz0 , it is unfortunately not straightforward with on-chain data as currently there isnt a native mapping for the inputs to redeemers. The alternative is to sort all inputs with tx.hash and tx.index and map using redeemer indexes.

@fallen-icarus - how dependent are you on this one? Is it something we can push to v1.1.2 - to avoid delays with re-building specs and tests or something corer to your work making it a blocker?

**Comment by fallen-icarus** [comment]
> Is it something we can push to v1.1.2

Yes, I think so. For now, I can use the datums so this isn't blocking me. I don't foresee this being a potential problem until after plutusV3 is released.

**Comment by rdlrt** [comment]
Perfect, so should be alright to club with other fork additions.
Thanks for confirming
