### ISSUE TITLE
`address_utxos` endpoint sometimes returns an empty list instead of the results

### ISSUE THREAD

**Issue by fallen-icarus** [cardano-community/koios-artifacts#283]
**Describe the bug**
I am trying to get the UTxOs for my address using the `address_utxos` endpoint for the preproduction testnet. This is the address:
`addr_test1qp9s80tz7l3dxmg4wcsd6fwnjcxuqul6wy6x5pwt98hmhj00c7g4mfe8tn70pveep8eep4dzuu0f784unh4wk5p7jkasa3cym4`

There are 2 UTxOs at the address. I am using this command:
```bash
curl -X POST "https://preprod.koios.rest/api/v1/address_utxos"  -H "accept: application/json" -H "content-type: application/json"  -d '{"_addresses":["addr_test1qp9s80tz7l3dxmg4wcsd6fwnjcxuqul6wy6x5pwt98hmhj00c7g4mfe8tn70pveep8eep4dzuu0f784unh4wk5p7jkasa3cym4"],"_extended":true}'
```

However, the endpoint returns an empty list about 30% of the time.

**To Reproduce**
Repeat the above command multiple times and see how often it returns an empty list instead of the two UTxOs. I am consistently seeing at least 2 or 3 empty lists out of every 10 queries.

**Expected behavior**
It should never return an empty list when there are in fact UTxOs at the address. It should either return the proper result or return an error that explains what happened.

**Comment by rdlrt** [comment]
Thanks for raising, looks like one of the instance was on fork - but not far enough from tip to be marked down.
![image](https://github.com/cardano-community/koios-artifacts/assets/3169068/c539b226-d714-4ca6-8835-20f7b502a75a)

Will adapt health check to prevent in future
