### ISSUE TITLE
koios tx_info returns error with some tx_hashes

### ISSUE THREAD

**Issue by larestrepo** [cardano-community/koios-artifacts#290]
**Describe the bug**
Using koios tx_info, the endpoint expects a list of tx_hashes; there are some hashes that return the following error:
```json
{
  "code": "22P02",
  "details": "Token \"(\" is invalid.",
  "hint": null,
  "message": "invalid input syntax for type json"
}
```
For example, the following tx_hash in preview: f596f2ff47190849b5d00967eba27a0b9301548965498fadf90265117de330b1 which is a valid hash as seen in cardano explorer: https://preview.cardanoscan.io/transaction/f596f2ff47190849b5d00967eba27a0b9301548965498fadf90265117de330b1

```bash
curl -X POST "https://preview.koios.rest/api/v1/tx_info" \
 -H "accept: application/json"\
 -H "content-type: application/json" \
 -d '{"_tx_hashes":["f596f2ff47190849b5d00967eba27a0b9301548965498fadf90265117de330b1"]}' \
```

**Comment by rdlrt** [comment]
Should be resolved as of Koios v1.2.0a on guild/preview/preprod
