### ISSUE TITLE
Increase payload limit for ogmios endpoints

### ISSUE THREAD

**Issue by fallen-icarus** [cardano-community/koios-artifacts#292]
**Is your feature request related to a problem? Please describe.**
I am trying to use Koios as a remote node for building transactions. When smart contracts are involved, the execution budgets must be estimated. However, submitting a transaction for estimation using the ogmios endpoint results in:

```
Payload too large, body length was 5933. Please ensure your request body size is below 5120 bytes
```

This limit makes it impossible to use Koios for estimating transactions larger than 5120 bytes. The wallet I am building is meant to enable users to fit as much as possible into a single transaction. An example transaction users may build:

```
1. Change delegation preferences for stake1.
2. Change delegation preferences for stake2.
3. Create new limit order for cardano-swaps.
4. Update existing limit order for cardano-swaps.
5. Make payment on loan with id XXX.
6. Send 10 ADA to a friend.
```

This all happens in a single transaction. But the 5120 byte limit makes it impossible to use Koios even though the above actually does fit within the limits of the current Cardano parameters.

(I haven't tested it since I haven't gotten passed the execution estimation step, but I am assuming this limit also exists for tx submission through the ogmios endpoints.)

**Describe the solution you'd like**
The limit should at least be the maximum transaction size (approximately 16000 bytes). I would be okay with only the ogmios endpoints having an increased limit.

**Describe alternatives you've considered**
The only alternatives are to use a local node, or another service provider instead of Koios.

**Comment by rdlrt** [comment]
Thanks for raising, will get this fixed shortly

**Comment by rdlrt** [comment]
Should be sorted
