### ISSUE TITLE
Add null as an acceptable asset_name

### ISSUE THREAD

**Issue by gobboo** [cardano-community/koios-artifacts#31]
**Is your feature request related to a problem? Please describe.**
So for my example I want to fetch royalty information of a policy / asset however I have to query every single asset of that policy using, asset_policy_info which is unnecessary data and leads to time outs and very long queries, the ability to fetch a single asset from a specific policy just to check the metadata would be nice so we could use asset_info but with a null asset_name as then we can fetch 1 asset from that policy instead of the 10,000 and so forth from the other one

**Describe the solution you'd like**
Null as an acceptable value on the asset_name field ( or for it to be optional ) so then it will fetch 1 asset, most likely the first one doesn't matter which one

**Describe alternatives you've considered**
None, this alternative was thought of by Priyank

**Additional context**
N/A

**Comment by rdlrt** [comment]
Accepting null as character in input field is specifically for specs, so that asset name is not mandatory, but we still would want to not list all assets by making the field optional in specs
