### ISSUE TITLE
Excessive `Gateway Timeout`s for `pool_info` endpoint on mainnet

### ISSUE THREAD

**Issue by fallen-icarus** [cardano-community/koios-artifacts#310]
**Describe the bug**
I am trying to query all of the registered pools and their information. First, I use the `pool_list` endpoint to get the `pool_id_bech32` for each registered pool. Then, grouping the pools 70 per query, I use the `pool_info` endpoint to get the info for each pool. Doing this, I consistently get a `504 Gateway Timeout` response for mainnet. I am doing the requests concurrently so I think only one or two koios instances are too slow.

I have tried doing 50 pools per query, but still ran into the `504 Gateway Timeout` response. Doing less than 50 pools per query results in me exceeding the burst limit (again doing them concurrently).

There is no issue doing 70 per query on the preproduction testnet (concurrently); I can get all of the registered pools and their information within 15-20 seconds.

As an example, this query tries to get the info for approximately 70 pools on mainnet:
```bash
curl -X POST "https://api.koios.rest/api/v1/pool_info"  -H "accept: application/json" -H "content-type: application/json"  -d '{"_pool_bech32_ids":["pool1z5uqdk7dzdxaae5633fqfcu2eqzy3a3rgtuvy087fdld7yws0xt","pool1pu5jlj4q9w9jlxeu370a3c9myx47md5j5m2str0naunn2q3lkdy","pool1q80jjs53w0fx836n8g38gtdwr8ck5zre3da90peuxn84sj3cu0r","pool1ddskftmsscw92d7vnj89pldwx5feegkgcmamgt5t0e4lkd7mdp8","pool1qqqqqdk4zhsjuxxd8jyvwncf5eucfskz0xjjj64fdmlgj735lr9","pool1dmqzwuql5mylffvn7ln3pr9j7kh4gdsssrmma5wgx56f6rtyf42","pool1qzlw7z5mutmd39ldyjnp8n650weqe55z5p8dl3fagac3ge0nx8l","pool16tcjctesjnks0p8sfrlf8f3d3vrp2fdn2msy80sgg3cdjtayu3z","pool1qzlwlpcsgflr9z3f24fg836tyq45p0kf5cnrp20s8v0psp6tdkx","pool1p9sda64t6l9802tsu2fj6phvt9xfqgcpjucyr3kek8wzurmn8rz","pool18xykgvvvxej2e5ap04ks72d8fdke4qsqeh30satznyrtj88634d","pool1qqq6qqa0hpzvumv5p87ynczfmdj557xuwlc3289ke42g72z7f74","pool1e556526sqwugxwnmeumt9lhj5jukklg8vv3ynk75xt9vs7adr5y","pool124lm97s6f4satl7xz0ulzgg6tv30tskry3zcntwrz68n60v5yne","pool1vx9tzlkgafernd9vpjpxkenutx2gncj4yn88fpq69823qlwcqrt","pool1m83drqwlugdt9jn7jkz8hx3pne53acfkd539d9cj8yr92dr4k9y","pool1krznhwu3h5pu2stuslr53z5rme50t6384macsmylcnljwc7yjky","pool12584mjtgz3fhgpx823qht56gycnfnezg6aqqthazv4qdxkd5c46","pool1jhzf2mm6zdlhl6w89uhgx8nq8p6ykcc86qq58vjy0ejyxrrksfj","pool13wzpwavanfpkr4r4j30plrlc6dn6p822lkt22zdllmy7q8y7s90","pool1df9rj4n0t3zlpak7xnh4ue6t3yh9zlw7a02w4l8askp77up25rt","pool1q3xdrewrldt06rpjx6pzguzm847ujxnmajxrsr7dsthscz4htlv","pool1u899yml96tf2cf4zkw4490mnhf832pk6fefnaluvt7487jmqzhg","pool1fh4sh2telea0tfdy39h0drx6uq566yt9gf24edpz7335sclx39z","pool1pk7cjkcdsawxf25dwml0ely8vhjx7wp7nqans3jwatanceyqae0","pool1g0hsnjnt0du3kp33gjua3npncngr3yg4ak2zfdhd4zvmy6r8hyd","pool14kg79f3v5lqfvp5etqvmy6m9kuzpnd80w5cl44qrl8tpuk00quc","pool1ekhy5xsgjaq38em75vevk8df0k0rljju77tljw288ys5kumqce5","pool1wz27a9pvd2jat98s375lxaaj7qxy405km4vzp83wn5vtwp59kvh","pool1d70vllztcsgx3ku8h5vnukzz2a7lpzjxfjmuqqvxtj9kq27hygs","pool14hsxa2zfwzvy9ncdjwnx0xkcltjmdydeayxfju7suuuewv0dnke","pool1qwa8x4u4a2pff0xdv0haxpgk3tyrvl5adl2lpf3ztcftqruhea0","pool1h5jtxde8j86qrnqzj32ugn480u7gw5xw8wqy5d227rl3vfg58qz","pool1gpz25s2aasmqnh9tg8a2rxmyxuvmj5s779htxk295e9ajnzjflc","pool1jk25l2pejpdzq8vdjlxrr05th49v9tgd78fqrtxvuw3rumpfc6t","pool1xxhs2zw5xa4g54d5p62j46nlqzwp8jklqvuv2agjlapwjx9qkg9","pool16kus5xvdysgmtjp0hhlwt72tsm0yn2zcn0a8wg9emc6c75lxvmc","pool1ld9hkah2dkzh73pvh9tf6xr0x28us34msv3zcv2sase5vhvq962","pool16fyda57p3c8gp5r6gmcq5tvqsp6mnzwvkxswgznkuh8wztrp6vv","pool190a9js7lk9lvmrngre7w268z9tz9xs9yz77audvw8ag4jerfdhx","pool1qqqyv9pn9typyqwcxqk5ewpxy5p27g5j2ms58hpp2c2kuzs5z77","pool1vxz0deezj5c2950e7arpzfqxzq8zd9kawsullrzjw5rsq0yhxgr","pool1smy2r8jdvgna5ykhe8rrch7h4qalyfafyzyh0rmanmq0jxptww7","pool14mm59ntjqzphjr6chrww639cdr3yjce4qcwzc5jkk38y22u7uc6","pool19f6guwy97mmnxg9dz65rxyj8hq07qxud886hamyu4fgfz7dj9gl","pool1spus7k8cy5qcs82xhw60dwwk2d4vrfs0m5vr2zst04gtq700gjn","pool1wll3vr4v605eap9hpjfpda5cjegqfkjt8hrz3kkxpnffqejhav3","pool1u3v7s93f2d968a8kce6zgfmckfx56ly626jkml6jv7tgweplrn8","pool1mcvq2z34f9cfdmkd97famsh20ekqtndw246ny5e8ug3mxfdf4zq","pool1jx4ss2zjage3cw0wht3450328y82yeprmq4fr3e2qtac2rhezkv","pool19uynx6nxcdksmaqdcshjg487fap3rs3axyhrdqa7gdqgzgxss4y","pool1gtphgrdj8sluxm9e7ca2spcwcq2p0dxj9zf5v0yv3gsagzq704n","pool1wm5quxelvgk8q50jyfznf9asvelp9zf0tk2wu4jazlw9yj4uctw","pool1lllmq2jgcqrag5c77lpc5m34fsqn63leadyx9tzx842n66ly3ql","pool1wjsshqjpl3n6zlscnfvyy9gxklkav2dvfyprfye6l0kewyvv6yj","pool1ft4xjlz9uw0r0ewcgtkgeakqrfc5azxmxwsm5pt94dv67mw4rgd","pool1ljlmfg7p37ysmea9ra5xqwccue203dpj40w6zlzn5r2cvjrf6tw","pool17ahr5ygy48vpdfnatqn2z4wfu2te4quapk2yx3k50ce6kd7feg0","pool1xrrrr8gldqz8pjxj6j8c638a9py04xuv66kfgn2dlsx9g52te0t","pool1x2h98z6e5xvrg5zw3v3dlu8hqdtj6lhp6r3w5ge7rvcqcx3pafq","pool1hwlghkwnjsjk8370qt3dvp23d7urwm36f95fmxcz3np2kghknj9","pool1nl74emh67vuyt8cgv6gwhjnrctxgrpqlrdzznj4l3lh5j8lj3ah","pool1k0xrqp03mn9u3q3sadndd6vu9udl5v38xpzyw0shm8sskuxw2av","pool1q66d2n39uvln4hazyzv8fyq977mpqus78sjd2369qfn7cptdeyh","pool1llxh8l0h8g9ghz3nrzh7ndvev4x43vnk72nsemzm795vxqs6dp8","pool19ejln2jcpg5dphc8m5nh8sya49sycsqj0v2cjxw6nku966cc8nu","pool1pvu2zdexh8wr4ggmuz90jvqrua6an43qj9m9urs785p8kwjzqwl","pool1etfar35l4tf6vam3gvqf5dnaq7levz32vgw4p00jzk7q7twg2te","pool1a600v0jd2z3yajazd80phln3exekumm7g56d9yvlrh6vx8dx2fc","pool1jyutduy73e5u9877uns3k9rm0tf4r24j8lrn4xtkjpl3q5sn5mw"]}'
```

The response from this query sometimes takes only 5 seconds while other times it take over a minute. (I don't know why it isn't returning a `504 Gateway Timeout` whenever it takes more than 30 seconds. I'm guessing it has something to do with `curl`.)

**To Reproduce**
Try the above example query several times and time how long it takes. For me, it ranges from 5s to 1m 15s.

**Expected behavior**
The variation in response times shouldn't be this large.

**Additional context**
I've recently open-sourced a [p2p desktop wallet](https://github.com/fallen-icarus/p2p-wallet/tree/dev) that uses Koios for everything. This issue appears whenever a user looks up all of the registered pools for mainnet. There is no issue with the preproduction testnet.

**Comment by rdlrt** [comment]
Pool info is a relatively heavy call that includes querying every delegator's stake/rewards. As a result, the timing will be inconsistent between instances. What informstion are you trying to bring across?

I do not think querying detailed info about each and every pool in a quuck succession is a good idea. Preprod (or any cardano testnet atm) has negligible history compared to mainnet, where size/performance/participation do not even come close.

Pool_list on the other end brings along most of the info that does not require querying all the details off each delegator.

Which fields are you particularly interested in?

**Comment by fallen-icarus** [comment]
Would it be possible to add `live_pledge` and `live_saturation` to `pool_list`? It has pretty much everything else I'm interested in right now.

**Comment by rdlrt** [comment]
live stake (pledge is light enough, as it's only against owners but saturation isnt) is where you are essentially querying all stake accounts delegated to a pool for their current balance, it is where majority of the query duration for pool_info is spent - as it is sum of all unspent tx outs for each stake account delegated to pool, in addition to rewards/mirs/treasury/withdrawal those accounts may have worked with. Add to that the not-so-common cases where delegator may not be part of epoch_stake, but would redelegate to this pool (which adds a lot of contention as for those we dont have baseline epoch stake to calculate delta against). This is why even node maintains active utxo set in memory, and consumes bulk of the 10-13GB  of ledger-state file on mainnet.

While this will seem bias avoiding complications above, I'd still recommend you to use active stake as indicator instead of live (as live stake isnt committed, an adversary can delegate to a pool in block 1 of epoch and undelegate at block 21000 of that epoch, degrading pool stats wildly) - and then drill down to live stake of pool on top subset found for first page of results (after sorting based on active stake).

**Comment by fallen-icarus** [comment]
> I'd still recommend you to use active stake as indicator instead of live (as live stake isnt committed, an adversary can delegate to a pool in block 1 of epoch and undelegate at block 21000 of that epoch, degrading pool stats wildly) - and then drill down to live stake of pool on top subset found for first page of results (after sorting based on active stake).

Okay, I can give this a shot if active stake is added to the pool_list endpoint.

**Comment by rdlrt** [comment]
`active_stake` is now added to `pool_list` and amended to v1.3.0. Should roll out to testnet instances over next few hours
