### ISSUE TITLE
Koios testnets are down

### ISSUE THREAD

**Issue by fallen-icarus** [cardano-community/koios-artifacts#317]
Sorry if this isn't the right place for this, but both the preproduction and preview testnet endpoints appear to not be working. For example, querying the cli_protocol_params endpoint using curl for both networks consistently gives:
```bash
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

The networks have been down for at least an hour at this point. Mainnet seems fine. Are they down for maintenance/upgrades? If they are, why aren't the updates being staggered so that the service isn't disrupted?

**Comment by fallen-icarus** [comment]
It's been almost 6 hrs now. I'm not getting the 503 error anymore, but the endpoints are taking a very long time to return results. The requests keep timing out.

**Comment by rdlrt** [comment]
There was an issue with nameservers upstream (as we didnt put much fallback on testnet's entrpoints as against mainnet), we've added a couple of public NS fallbacks - should be sorted now
