### ISSUE TITLE
Make API spec definition dynamic based on network in grest-poll.sh

### ISSUE THREAD

**Issue by DamjanOstrelic** [cardano-community/koios-artifacts#56]
**Is your feature request related to a problem? Please describe.**
When setting up grest on a network other than mainnet, the polling API spec definition will point to mainnet.

**Describe the solution you'd like**
When installing a network other than mainnet, grest-poll.sh should point to that network's API spec.

**Describe alternatives you've considered**
Keep manually editing the definition on new installs.

**Comment by rdlrt** [comment]
Added fix via `setup-grest.sh` (only for default, not user variable section) instead of `grest-poll sh` to:
1. avoid scraping on each poll (as you'd poll frequently, especially on monitoring instances)
2. Avoid third iteration of NWMAGIC (currently in env and setup-grest.sh)
