### ISSUE TITLE
Documentation | fingerprint field is missing in Transaction Info inputs -> asset_list fields

### ISSUE THREAD

**Issue by edridudi** [cardano-community/koios-artifacts#77]
## Documentation:
![image](https://user-images.githubusercontent.com/3818746/184532600-f68cbd52-b471-44bc-b5ed-cf59628841cc.png)

## Actual:
![image](https://user-images.githubusercontent.com/3818746/184532580-2fb71972-1d5f-4bc1-ac44-d7c14223340b.png)

**Comment by rdlrt** [comment]
Closed by #79
