### ISSUE TITLE
Koios-BF Metalabels count field Gap

### ISSUE THREAD

**Issue by edridudi** [cardano-community/koios-artifacts#80]
## BF's Model 
![image](https://user-images.githubusercontent.com/3818746/184535354-8d52e802-ca3b-4619-ae07-8eaed70772c3.png)

## Koios Model
![image](https://user-images.githubusercontent.com/3818746/184535384-7e3800eb-a301-48f0-bbf3-f249eb36cd94.png)

* PS: cip10 field is always null in BF so it might not be as important.

**Comment by rdlrt** [comment]
Need to ask - what would be the consumer facing use-case to add this?
Looking at the speed at which some of these are getting added, it almost looks to be candidate for seperate cache instance - which isnt an issue to add, if there is really demand for the count of a particulat label at all.

**Comment by edridudi** [comment]
Good question,
I don't have the answer for it though ...
I'm just exposing the gaps.
To tell you the truth, I don't see the use case of the metalabels endpoint as a whole.

**Comment by rdlrt** [comment]
True, `metalabels` by itself is quite rarely, maintaining a cache for count seems an overkill, even if minor. Would close this one for now - can revisit if there's an actual use case to the query.
