### ISSUE TITLE
GET /pool_blocks does not provide current epoch data

### ISSUE THREAD

**Issue by staking4ada** [cardano-community/koios-artifacts#92]
Documentation mentions:

Return information about blocks minted by a given pool in current epoch (or _epoch_no if provided)

However, instead of current epoch, data for epoch 294 is returned.

Example:

"https://api.koios.rest/api/v0/pool_blocks?_pool_bech32=pool10efuydxjnasr0309lqklmj9xahupdnzqd59r5dqjeh4twz06tr0"

does not return current pool blocks for current epoch, but for epoch 294.

**Comment by dostrelith678** [comment]
You're right, it gets ALL the blocks from the pool if _epoch_no is not provided. Documentation should be updated to reflect that.

**Comment by rdlrt** [comment]
Closed in #83
